const Map<String, String> ar = {
  //Login
  'welcomeTitle': 'أهلا بك مجددا',
  'welcomeText': 'يرجى تسجيل الدخول الى الحساب الخاص بك',
  'emailHint': 'أدخل البريد الالكتروني الخاص بك',
  'passwordHint': 'أدخل كلمة السر الخاصة بك',
  'forgetPasswordText': 'هل نسيت كلمة السر؟',
  'continueButton': 'متابعة',
  'continueWithGoogleButton': 'متابعة باستخدام غوغل',
  'skipButton': 'تخطي',
  'dontHaveAnAccountText': ' ليس لديك حساب؟',
  'createOneText': 'أنشئ واحدا',
  'createAccountText': 'انشاء حساب',
  'nameHint': 'أدخل الاسم الخاص بك',
  'confirmPasswordHint': 'تأكيد كلمة السر الخاصة بك',
  'loginText': 'تسجيل دخول',
  'haveAnAccountText': 'لديك حساب؟ ',
  'getFullAccessMessage': 'احصل على وصول كامل',
  //Home
  'categoriesTitle': ' الفئات',
  'brandsTitle': 'العلامات التجارية',
  'featuredProductsTitle': 'المنتجات المميزة',
  'homeItem': 'الرئيسية',
  'notificationsItem': 'الاشعارات',
  'myBagItem': 'سلة الشراء',
  'favouritesItem': 'المفضلة',
  'profileItem': 'الحساب',
  //Drawer
  'timezoneUserTitle': 'مستخدم Timezone',
  'ordersTitle': 'الطلبات',
  'topSalesTitle': 'الأكثر طلباً',
  'languageTitle': 'اللغة',
  'arLanguage': 'العربية',
  'enLanguage': 'الانكليزية',
  'logoutText': 'تسجيل خروج',
  //Product
  'brandTitle': 'العلامة التجارية: ',
  'rNumberTitle': 'الرقم: ',
  'genderTitle': 'الجنس: ',
  'movementTitle': 'الحركة: ',
  'caseSizeTitle': 'الحجم: ',
  'addToCartButton': 'أضف الى السلة',
  'woman': 'نسائي',
  'men': 'رجالي',
  //Cart
  'shoppingCartTitle': 'سلة التسوق',
  'totalText': 'المبلغ الكلي: ',
  'discountText': 'الخصم: ',
  'netValueText': 'المبلغ الصافي: ',
  'checkOutButton': 'متابعة الطلب',
  'checkOut': 'إرسال الطلب',
  'enterQuantityMessage': 'يرجى ادخال الكمية الجديدة: ',
  'quantityHint': 'أدخل الكمية الجديدة',
  'editButton': 'تعديل',
  'qtyTitle': 'الكمية: ',
  'priceTitle': 'السعر: ',
  //Checkout
  'sendOrderTitle': 'إرسال الطلب',
  'addressHint': 'قم بادخال عنوانك',
  'phoneNumberHint': 'قم بادخال رقم للتواصل',
  'notesHint': 'ملاحظات',
  'paymentMethodTitle': 'طريقة الدفع',
  'cashPaymentTitle': 'دفع مباشر ',
  'onlinePaymentTitle': 'دفع الكتروني ',
  'enterCardNumberHint': 'أدخل رقم البطاقة',
  //Orders
  'orderStatusTitle': 'حالة الطلب: ',
  'orderValueTitle': 'قيمة الطلب: ',
  //Order
  'orderNumberTitle': 'رقم الطلب: ',
  'orderDetailsTitle': 'تفاصيل الطلب: ',
  'individualText': 'الافرادي: ',
  'receivedOrderStatus': 'تم الاستلام',
  'checkOrderStatus': 'قيد التدقيق',
  'processOrderStatus': 'قيد التجهيز',
  'deliveryOrderStatus': 'قيد التوصيل',
  'deliveredOrderStatus': 'تم التوصيل',
  //Profile
  'profileTitle': 'حسابي',
  'leaveEmptyHint': 'اتركه فارغ لتجنب التغيير',
  'updateProfileInfoButton': 'تحديث معلومات الحساب',
  //Favourites
  'favouritesTitle': ' المفضلة ',
  //SnackBars
  'welcomeMessage': 'مرحبا ',
  'successMessage': 'تمت الاضافة بنجاح',
  'notMatchMessage': 'بياناتك لا تتطابق مع سجلاتنا',
  'requiredFieldMessage': 'يرجى تعبئة الحقول المطلوبة للمتابعة',
  'addingSuccessMessage': 'تمت الاضافة بنجاح',
  'updateSuccessMessage': 'تم تحديث المعلومات بنجاح',
  'removeSuccessMessage': 'تمت الازالة بنجاح',
  'emptyOrderMessage': 'لا يمكن انشاء طلب فارغ',
  'connectionErrorMessage': 'خطأ في الطلب , يرجى التأكد من اتصالك بالانترنت',
  'cardNumberVerifyMessage': 'يرجى التأكد من رقم البطاقة',
  'orderSendingSuccessMessage': 'تم إرسال الطلب بنجاح',
  //addons
  "no_noti": "لا توجد إشعارات",
  //Search
  'searchTitle': 'بحث',
  'noResultText': 'لا يوجد نتيجة',
};
