const Map<String, String> ar = {
  //Login
  'welcomeTitle': 'أهلا بك مجددا',
  'welcomeMessage': 'يرجى تسجيل الدخول الى الحساب الخاص بك',
  'emailHint': 'أدخل البريد الالكتروني الخاص بك',
  'passwordHint': 'أدخل كلمة السر الخاصة بك',
  'forgetPasswordText': 'هل نسيت كلمة السر؟',
  'continueButton': 'متابعة',
  'continueWithGoogleButton': 'متابعة باستخدام غوغل',
  'skipButton': 'تخطي',
  'dontHaveAnAccountText': ' ليس لديك حساب؟',
  'createOneText': 'أنشئ واحدا',
  'createAccountText': 'انشاء حساب',
  'nameHint': 'أدخل الاسم الخاص بك',
  'confirmPasswordHint': 'تأكيد كلمة السر الخاصة بك',
  'loginText': 'تسجيل دخول',
  'haveAnAccountText': 'لديك حساب؟ ',
  'getFullAccessMessage': 'احصل على وصول كامل',
  //Home
  'categoriesTitle': ' الفئات',
  'brandsTitle': 'العلامات التجارية',
  'featuredProductsTitle': 'المنتجات المميزة',
  'homeTitle': 'الرئيسية',
  'notificationsTitle': 'الاشعارات',
  'myBagTitle': 'سلتي',
  'favouritesTitle': 'المنتجات المفضلة',
  'profileTitle': 'الحساب',
  //Drawer
  'timezoneUserTitle': 'مستخدم Timezone',
  'topSalesTitle': 'أعلى مبيعات',
  'languageTitle': 'اللغة',
  'arLanguage': 'العربية',
  'enLanguage': 'الانكليزية',
  'logoutText': 'تسجيل خروج'
};
