const Map<String, String> ar = {
  //Login
  'welcomeTitle': 'أهلا بك مجددا',
  'welcomeText': 'يرجى تسجيل الدخول الى الحساب الخاص بك',
  'emailHint': 'أدخل البريد الالكتروني الخاص بك',
  'passwordHint': 'أدخل كلمة السر الخاصة بك',
  'forgetPasswordText': 'هل نسيت كلمة السر؟',
  'continueButton': 'متابعة',
  'continueWithGoogleButton': 'متابعة باستخدام غوغل',
  'skipButton': 'تخطي',
  'dontHaveAnAccountText': ' ليس لديك حساب؟',
  'createOneText': 'أنشئ واحدا',
  'createAccountText': 'انشاء حساب',
  'nameHint': 'أدخل الاسم الخاص بك',
  'confirmPasswordHint': 'تأكيد كلمة السر الخاصة بك',
  'loginText': 'تسجيل دخول',
  'haveAnAccountText': 'لديك حساب؟ ',
  'getFullAccessMessage': 'احصل على وصول كامل',
  //Home
  'categoriesTitle': ' الفئات',
  'brandsTitle': 'العلامات التجارية',
  'featuredProductsTitle': 'المنتجات المميزة',
  'homeItem': 'الرئيسية',
  'notificationsItem': 'الاشعارات',
  'myBagItem': 'سلتي',
  'favouritesItem': 'المنتجات المفضلة',
  'profileItem': 'الحساب',
  //Drawer
  'timezoneUserTitle': 'مستخدم Timezone',
  'topSalesTitle': 'أعلى المبيعات',
  'languageTitle': 'اللغة',
  'arLanguage': 'العربية',
  'enLanguage': 'الانكليزية',
  'logoutText': 'تسجيل خروج',
  //Product
  'brandTitle': 'العلامة التجارية: ',
  'rNumberTitle': 'الرقم: ',
  'genderTitle': 'الجنس: ',
  'movementTitle': 'الحركة: ',
  'caseSizeTitle': 'الحجم: ',
  'addToCartButton': 'أضف الى السلة',
  //Cart
  'shoppingCartTitle': 'سلة التسوق',
  'totalText': 'المبلغ الكلي: ',
  'discountText': 'الخصم: ',
  'netValueText': 'المبلغ الصافي: ',
  'checkOutButton': 'ادفع',
  'enterQuantityMessage': 'يرجى ادخال الكمية الجديدة: ',
  'quantityHint': 'أدخل الكمية الجديدة',
  'editButton': 'تعديل',
  'qtyTitle': 'الكمية: ',
  'priceTitle': 'السعر: ',
  //Profile
  'profileTitle': 'حسابي',
  'leaveEmptyHint': 'اتركه فارغ لتجنب التغيير',
  'updateProfileInfoButton': 'تحديث معلومات الحساب',
  //Favourites
  'favouritesTitle': 'المنتجات المفضلة: ',
  //SnackBars
  'welcomeMessage': 'مرحبا ',
  'successMessage': 'تمت الاضافة بنجاح',
  'notMatchMessage': 'بياناتك لا تتطابق مع سجلاتنا',
  'requiredFieldMessage': 'يرجى تعبئة الحقول المطلوبة للمتابعة',
  'addingSuccessMessage': 'تمت الاضافة بنجاح',
  'updateSuccessMessage': 'تم تحديث المعلومات بنجاح',
  'removeSuccessMessage': 'تمت الازالة بنجاح',
};
