const Map<String, String> en = {
  //Auth
  'welcomeTitle': 'Welcome Back',
  'welcomeMessage': 'Please Sign In To Your Account',
  'emailHint': 'Enter Your Email',
  'passwordHint': 'Enter Your Password',
  'forgetPasswordText': 'Forget Password?',
  'continueButton': 'Continue',
  'continueWithGoogleButton': 'Continue With Google',
  'skipButton': 'skip',
  'dontHaveAnAccountText': 'Don\'t Have an Account? ',
  'createOneText': 'Create One',
  'createAccountText': 'Create Account',
  'nameHint': 'Enter Your Name',
  'confirmPasswordHint': 'Confirm Your Password',
  'loginText': 'Login',
  'haveAnAccountText': 'Have an Account? ',
  'getFullAccessMessage': 'Get Full Access',
  //Home
  'categoriesTitle': 'Categories',
  'brandsTitle': 'Brands',
  'featuredProductsTitle': 'Featured Products',
  //Bottom Navigation Bar
  'homeTitle': 'Home',
  'notificationsTitle': 'Notifications',
  'myBagTitle': 'My Bag',
  'favouritesTitle': 'Favourites',
  'profileTitle': 'Profile',
  //Drawer
  'timezoneUserTitle': 'Timezone User',
  'topSalesTitle': 'Top Sales',
  'languageTitle': 'Language',
  'arLanguage': 'Arabic',
  'enLanguage': 'English',
  'logoutText': 'Logout',
  //Product
  'brandTitle': 'Brand: ',
  'rNumberTitle': 'R.Number: ',
  'genderTitle': 'Gender: ',
  'movementTitle': 'Movement: ',
  'caseSizeTitle': 'Case size: ',
  'addToCartButton': 'Add to Cart: ',
  //Cart
  'shoppingCartTitle': 'Shopping Cart',
  'totalText': 'Total:',
  'discountText': 'Discount:',
  'netValueText': 'Net Value:',
  'checkOutButton': 'Check Out:',
  'enterQuantityMessage': 'Please Enter a New Quantity: ',
  'quantityHint': 'Enter a New Quantity',
  'editButton': 'Edit',
  //SnackBars
  'successMessage': 'Added Successfully',
};
